apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstream-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstream-app
  template:
    metadata:
      labels:
        app: kstream-app
    spec:
      containers:
        - name: kstream-app
          image: 4dori/kstream-app:11.0.0
